server:
  port: 8081
spring:
  profiles:
    active: dev

---

server:
  port: 8083

spring:
  profiles: dev
---
server:
  port: 8084

spring:
  profiles: prod










#person:
#    age: 18
#    boss: false
#    birth: 2020/3/1
#    maps: {k1: v1,k2: 12}
#    lists:
#      - lisi
#      - zhaoliu
#    dog:
#      name: 小狗
#      age: 4
#    last-nmae: zhangsan