server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  # Eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向Eureka注册中心注册自己。此处自己不需要注册
    fetch-registry: false   # false 表示自己为注册中心
    service-url:    # 监控页面。defaultZone参数可在EurekaClientConfigBean（cmd+点击 进入查看）中查看
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/